name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 3.0.1
homepage: https://github.com/sbis04/video_trimmer
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.7.2
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Spill-App/ffmpeg_kit_flutter.git
      ref: 908251be13edc4aac74fb5669615f366b13b6ccf
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  intl: ^0.19.0
  path: ^1.8.3
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.1

flutter:
