name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 5.0.0
homepage: https://github.com/sbis04/video_trimmer
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.5
  ffmpeg_kit_flutter_full_gpl:
    git:
      url: https://github.com/Spill-App/ffmpeg_kit_flutter.git
      ref: 423153bc0cdd1505e1894225164829e561da058a
  video_thumbnail:
    git:
      url: https://github.com/Spill-App/video_thumbnail_fork.git
      ref: b0eea86167f93d32375c4500861edecbd66cf80a
  path_provider: ^2.1.5
  intl: ^0.20.2
  path: ^1.9.1
  get_thumbnail_video: ^0.7.3
  flutter_native_video_trimmer: ^1.1.9
  transparent_image: ^2.0.1
  image: ^4.5.4

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.0.0

flutter:
